# Generated by Django 2.0.2 on 2019-03-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='description',
            field=models.CharField(default='', max_length=300, verbose_name='Descripción'),
        ),
    ]
