# Generated by Django 2.1 on 2018-12-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colections', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colection',
            options={'ordering': ['order', 'title'], 'verbose_name': 'coleccion', 'verbose_name_plural': 'colecciones'},
        ),
        migrations.RemoveField(
            model_name='colection',
            name='content',
        ),
        migrations.RemoveField(
            model_name='colection',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='colection',
            name='order',
            field=models.SmallIntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='colection',
            name='image',
            field=models.ImageField(upload_to='colections', verbose_name='Portada'),
        ),
    ]
