# Generated by Django 2.1 on 2018-12-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colections', '0002_auto_20181205_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='colection',
            name='content',
            field=models.CharField(default='', max_length=300, verbose_name='Chamuyo'),
        ),
    ]
