# Generated by Django 2.1 on 2018-12-07 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colections', '0003_colection_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColectionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='colections', verbose_name='Fotos')),
                ('colection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='colections.Colection')),
            ],
            options={
                'verbose_name': 'imagen',
                'verbose_name_plural': 'imagenes',
            },
        ),
    ]
