# Generated by Django 2.1 on 2018-12-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrusel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrusel',
            name='image',
            field=models.ImageField(upload_to='carrusel', verbose_name='Imagen'),
        ),
    ]
